
package jadi;

/**
 *
 * @author Priyo
 */
import java.io.*;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
public class JadiGUI_LihatEdit extends javax.swing.JFrame {

    /** Creates new form JadiGUI2 */
    private DefaultTableModel model,identitas_model,sarana;
    public JadiGUI_LihatEdit() throws SQLException {
        initComponents();
        this.setLocationRelativeTo(this);
        model=new DefaultTableModel();
        jTable1.setModel(model);
        model.addColumn("nama_ruang");
        model.addColumn("kondisi_lantai");
        model.addColumn("dinding");
        model.addColumn("atap");
        model.addColumn("pintu");
        model.addColumn("jendela");
        model.addColumn("sirkulasi");
        model.addColumn("cahaya");
        model.addColumn("lembab");
        model.addColumn("suhu");
        model.addColumn("bising");
        model.addColumn("bau");
        model.addColumn("bocor");
        model.addColumn("rusak");
        model.addColumn("aus");
        model.addColumn("kokoh");
        model.addColumn("kunci");
        
        baca();
        
        identitas_model=new DefaultTableModel();
        table_identitas.setModel(identitas_model);
        identitas_model.addColumn("nama ruang");
        identitas_model.addColumn("lokasi");
        identitas_model.addColumn("jurusan");
        identitas_model.addColumn("fakultas");
        identitas_model.addColumn("panjang");
        identitas_model.addColumn("lebar");
        identitas_model.addColumn("kursi");
        identitas_model.addColumn("pintu");
        identitas_model.addColumn("jendela");
        
        baca_identitas();
        
        sarana=new DefaultTableModel();
        tablesaran.setModel(sarana);
        sarana.addColumn("nama_ruang");
        sarana.addColumn("stop kontak");
        sarana.addColumn("kabel_lcd");
        sarana.addColumn("jumlah_lampu");
        sarana.addColumn("jumlah_kipas");
        sarana.addColumn("jumlah_ac");
        sarana.addColumn("jumlah_cctv");
        sarana.addColumn("ssid");
        sarana.addColumn("konsisi_kontak");
        sarana.addColumn("kondisi_lcd");
        sarana.addColumn("kondisi_lampu");
        sarana.addColumn("kondisi_kipas");
        sarana.addColumn("kondisi_ac");
        sarana.addColumn("kondisi_cctv");
        sarana.addColumn("bandwidth");
        sarana.addColumn("posisi_kontak");
        sarana.addColumn("posisi_lcd");
        sarana.addColumn("posisi_lampu");
        sarana.addColumn("posisi_kipas");
        sarana.addColumn("posisi_ac");
        sarana.addColumn("posisi_cctv");
        sarana.addColumn("status");
        
        baca_sarana();
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        table_identitas = new javax.swing.JTable();
        hapus_identitas = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        hapus_lingkungan = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablesaran = new javax.swing.JTable();
        hapus_sarana = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jLabel1.setText("Nama Ruang");

        jLabel2.setText("Informasi Ruang");

        table_identitas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(table_identitas);

        jButton1.setText("hapus identitas");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(45, 45, 45)
                        .addComponent(jLabel2))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(hapus_identitas, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addComponent(jButton1)))
                .addContainerGap(378, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hapus_identitas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addContainerGap(214, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Tampil Identitas", jPanel2);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable1);

        jButton2.setText("Hapus Lingkungan");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 820, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(hapus_lingkungan, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(jButton2)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(36, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hapus_lingkungan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addGap(296, 296, 296))
        );

        jTabbedPane1.addTab("Tampil Lingkungan", jPanel3);

        tablesaran.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablesaran);

        jButton3.setText("Hapus Sarana");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 773, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(hapus_sarana, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46)
                        .addComponent(jButton3)))
                .addContainerGap(57, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hapus_sarana, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3))
                .addGap(0, 250, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Tampil Sarana", jPanel4);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addGap(40, 40, 40))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       String hapus=hapus_identitas.getText();
        try{
           Connection coon=Koneksinya_ruang.getKonksi();
           String sql="DELETE FROM IDENTITAS WHERE NAMA_RUANG=?";
           PreparedStatement p=coon.prepareStatement(sql);
           
           p.setString(1, hapus);
           JOptionPane.showMessageDialog(this, "hapus data sukses");
           p.executeUpdate();
           p.close();
           
           
       }catch(SQLException q){
           JOptionPane.showMessageDialog(this, "gagal hapus data"+q);
       }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String hapus=hapus_lingkungan.getText();
        try{
           Connection coon=Koneksinya_ruang.getKonksi();
           String sql="DELETE FROM LINGKUNGAN WHERE NAMA_RUANG=?";
           PreparedStatement p=coon.prepareStatement(sql);
           
           p.setString(1, hapus);
           JOptionPane.showMessageDialog(this, "hapus data sukses");
           p.executeUpdate();
           p.close();
           
           
       }catch(SQLException q){
           JOptionPane.showMessageDialog(this, "gagal hapus data"+q);
       }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        String hapus=hapus_sarana.getText();
        try{
           Connection coon=Koneksinya_ruang.getKonksi();
           String sql="DELETE FROM SARANA WHERE NAMA_RUANG=?";
           PreparedStatement p=coon.prepareStatement(sql);
           
           p.setString(1, hapus);
           JOptionPane.showMessageDialog(this, "hapus data sukses");
           p.executeUpdate();
           p.close();
           
           
       }catch(SQLException q){
           JOptionPane.showMessageDialog(this, "gagal hapus data"+q);
       }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JadiGUI_LihatEdit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JadiGUI_LihatEdit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JadiGUI_LihatEdit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JadiGUI_LihatEdit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new JadiGUI_LihatEdit().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(JadiGUI_LihatEdit.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }
    
    
    void baca_identitas(){
        identitas_model.getDataVector().removeAllElements();
        identitas_model.fireTableDataChanged();
        
        try{
            Connection con=Koneksinya_ruang.getKonksi();
            Statement st=con.createStatement();
            
            String sql="SELECT * FROM IDENTITAS";
            ResultSet rs=st.executeQuery(sql);
            
            while(rs.next()){
                Object[] bj=new Object[9];
                bj[0]=rs.getString("nama_ruang");
                bj[1]=rs.getString("lokasi");
                bj[2]=rs.getString("fakultas");
                bj[3]=rs.getString("jurusan");
                bj[4]=rs.getString("panjang");
                bj[5]=rs.getString("lebar");
                bj[6]=rs.getString("jumlah_kursi");
                bj[7]=rs.getString("jumlah_pintu");
                bj[8]=rs.getString("jumlah_jendela");
                identitas_model.addRow(bj);
            }
            rs.close();
            st.close();
        }catch(SQLException q){
            JOptionPane.showMessageDialog(this, "gagal load data"+q);
        }
    }
    
    void baca_sarana(){
        sarana.getDataVector().removeAllElements();
        sarana.fireTableDataChanged();
        
        try{
            Connection cmt=Koneksinya_ruang.getKonksi();
            Statement sq=cmt.createStatement();
            
            String sql="SELECT * FROM SARANA";
            ResultSet rq=sq.executeQuery(sql);
            
            while(rq.next()){
                Object[] b=new Object[22];
                b[0]=rq.getString("nama_ruang");
                b[1]=rq.getString("jumlah_stop_kontak");
                b[2]=rq.getString("jumblah_kabel_lcd");
                b[3]=rq.getString("jumlah_lampu");
                b[4]=rq.getString("jumlah_kipas");
                b[5]=rq.getString("jumlah_ac");
                b[6]=rq.getString("jumlah_cctv");
                b[7]=rq.getString("ssid");
                b[8]=rq.getString("kondisi_kontak");
                b[9]=rq.getString("kondisi_lcd");
                b[10]=rq.getString("kondisi_lampu");
                b[11]=rq.getString("kondisi_kipas");
                b[12]=rq.getString("kondisi_ac");
                b[13]=rq.getString("kondisi_cctv");
                b[14]=rq.getString("banwidth");
                b[15]=rq.getString("posisi_kontak");
                b[16]=rq.getString("posisi_lcd");
                b[17]=rq.getString("posisi_lampu");
                b[18]=rq.getString("posisi_kipas");
                b[19]=rq.getString("posisi_ac");
                b[20]=rq.getString("posisi_cctv");
                b[21]=rq.getString("apa_login");
                sarana.addRow(b); 
            }
            rq.close();
            sq.close();
        }catch(SQLException e){
            JOptionPane.showMessageDialog(this, "gagal tampil data"+e);
        }
    }
    
    void baca() throws SQLException {
        model.getDataVector().removeAllElements();
        model.fireTableDataChanged();
        try{
            Connection c=Koneksinya_ruang.getKonksi();
            Statement s=c.createStatement();
            
            String sql="SELECT * FROM LINGKUNGAN";
            ResultSet r=s.executeQuery(sql);
            
            while(r.next()){
                Object[] ob=new Object[17];
                ob[0]=r.getString("nama_ruang");
                ob[1]=r.getString("kondisi_lantai");
                ob[2]=r.getString("kondisi_dinding");
                ob[3]=r.getString("kondisi_atap");
                ob[4]=r.getString("kondisi_pintu");
                ob[5]=r.getString("kondisi_jendela");
                ob[6]=r.getString("sirkulasi");
                ob[7]=r.getString("nilai_cahaya");
                ob[8]=r.getString("tingkat_lembab");
                ob[9]=r.getString("suhu");
                ob[10]=r.getString("bising");
                ob[11]=r.getString("bau");
                ob[12]=r.getString("bocor");
                ob[13]=r.getString("rusak");
                ob[14]=r.getString("aus");
                ob[15]=r.getString("kokoh");
                ob[16]=r.getString("kunci_ada");
                model.addRow(ob);
            }
            r.close();
            s.close();
        }catch(SQLException e){
            JOptionPane.showMessageDialog(this, "gagal tampil ke table"+e);
        }
    
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField hapus_identitas;
    private javax.swing.JTextField hapus_lingkungan;
    private javax.swing.JTextField hapus_sarana;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable table_identitas;
    private javax.swing.JTable tablesaran;
    // End of variables declaration//GEN-END:variables

}
