
package jadi;

import javax.swing.ButtonGroup;
import javax.swing.ComboBoxModel;
import javax.swing.JComboBox;
import java.awt.event.*;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonModel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;


/**
 *
 * @author Priyo
 */
public class JadiGUI_Isi extends javax.swing.JFrame{
    JadiGUI_Pilihan pilih = new JadiGUI_Pilihan();
        

    /**
     * Creates new form JadiGUI3
     */
    //JComboBox combo=new JComboBox();
    //JTextField jurusan;
    ButtonGroup lantai = new ButtonGroup();
    ButtonGroup kontak = new ButtonGroup();
    ButtonGroup lcd = new ButtonGroup();
    ButtonGroup dinding = new ButtonGroup();
    ButtonGroup atap = new ButtonGroup();
    ButtonGroup pintu = new ButtonGroup();
    ButtonGroup jendela = new ButtonGroup();
    ButtonGroup bising = new ButtonGroup();
    ButtonGroup bau = new ButtonGroup();
    ButtonGroup bocor = new ButtonGroup();
    ButtonGroup rusak = new ButtonGroup();
    ButtonGroup aus = new ButtonGroup();
    ButtonGroup kokoh = new ButtonGroup();
    ButtonGroup kunci = new ButtonGroup();
   
    
   // private ActionEvent ItemEvent;
    kenalan l=new kenalan();
    //Lingkungan ling=new Lingkungan();
    public JadiGUI_Isi() {
       kenalan l=new kenalan();
        //l.setNamaRuang(null);= input_jurusan;
        
        initComponents();
        this.setLocationRelativeTo(this);
        
        ButtonGroup kontak = new ButtonGroup();
        kontak.add(RD_kontak1);
        kontak.add(RD_kontak2);
        
        ButtonGroup lcd = new ButtonGroup();
        lcd.add(RD_LCD1);
        lcd.add(RD_LCD2);
        
        ButtonGroup lampu = new ButtonGroup();
        lampu.add(RD_lampu1);
        lampu.add(RD_lampu2);
        
        ButtonGroup kipas = new ButtonGroup();
        kipas.add(RD_kipas1);
        kipas.add(RD_kipas2);
        
        ButtonGroup ac = new ButtonGroup();
        ac.add(RD_AC1);
        ac.add(RD_AC2);
        
        ButtonGroup cctv = new ButtonGroup();
        cctv.add(RD_CCTV1);
        cctv.add(RD_CCTV2);
        
        ButtonGroup login = new ButtonGroup();
        login.add(RD_Login1);
        login.add(RD_Login2);
        
        ButtonGroup lantai = new ButtonGroup();
        lantai.add(lantai_bersih);
        lantai.add(lantai_kotor);
        
        ButtonGroup dinding = new ButtonGroup();
        dinding.add(dinding_bersih);
        dinding.add(dinding_kotor);
        
        ButtonGroup atap = new ButtonGroup();
        atap.add(atap_bersih);
        atap.add(atap_kotor);
        
        ButtonGroup pintu = new ButtonGroup();
        pintu.add(pintu_bersih);
        pintu.add(pintu_kotor);
        
        ButtonGroup jendela = new ButtonGroup();
        jendela.add(jendela_bersih);
        jendela.add(jendela_kotor);
        
        ButtonGroup bising = new ButtonGroup();
        bising.add(ini_bising);
        bising.add(ini_gakbising);
        
        ButtonGroup bau = new ButtonGroup();
        bau.add(ini_bau);
        bau.add(ini_gakbau);
        
        ButtonGroup bocor = new ButtonGroup();
        bocor.add(ini_bocor);
        bocor.add(ini_gakbocor);
        
        ButtonGroup rusak = new ButtonGroup();
        rusak.add(ada_rusak);
        rusak.add(gak_ada_rusak);
        
        ButtonGroup aus = new ButtonGroup();
        aus.add(sudah_aus);
        aus.add(durung_aus);
        
        ButtonGroup kokoh = new ButtonGroup();
        kokoh.add(kokoh_1);
        kokoh.add(kokoh_2);
        
        ButtonGroup kunci = new ButtonGroup();
        kunci.add(kunciada);
        kunci.add(kunchilang);
        
        ButtonGroup aman = new ButtonGroup();
        aman.add(RD_aman);
        aman.add(tidak);
         //Lingkungan ling=new Lingkungan();
        
        
       // combo=new JCombbox(jComboBox3);
//        System.out.println(RD_LCD1.getText());
//        System.out.println(jComboBox4.getSelectedIndex());
//        Object a[] = new Object[] {1, 2, 3, 4};
//        JComboBox b = new JComboBox(a);
//        
        //jComboBox3.addItem(fai.length);
        
        //jComboBox3.addItem(a[0]);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        inputnama_ruang = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        input_jurusan = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        input_p = new javax.swing.JTextField();
        input_l = new javax.swing.JTextField();
        input_kursi = new javax.swing.JTextField();
        j_jendela = new javax.swing.JTextField();
        j_pintu = new javax.swing.JTextField();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jComboBox4 = new javax.swing.JComboBox();
        RD_kontak1 = new javax.swing.JRadioButton();
        RD_kontak2 = new javax.swing.JRadioButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jTextField11 = new javax.swing.JTextField();
        jTextField12 = new javax.swing.JTextField();
        jTextField13 = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        jTextField14 = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jTextField15 = new javax.swing.JTextField();
        jTextField16 = new javax.swing.JTextField();
        RD_LCD1 = new javax.swing.JRadioButton();
        RD_LCD2 = new javax.swing.JRadioButton();
        RD_lampu2 = new javax.swing.JRadioButton();
        RD_lampu1 = new javax.swing.JRadioButton();
        RD_kipas2 = new javax.swing.JRadioButton();
        RD_kipas1 = new javax.swing.JRadioButton();
        RD_AC2 = new javax.swing.JRadioButton();
        RD_AC1 = new javax.swing.JRadioButton();
        RD_CCTV1 = new javax.swing.JRadioButton();
        RD_Login2 = new javax.swing.JRadioButton();
        RD_CCTV2 = new javax.swing.JRadioButton();
        RD_Login1 = new javax.swing.JRadioButton();
        jComboBox5 = new javax.swing.JComboBox();
        jComboBox6 = new javax.swing.JComboBox();
        jComboBox7 = new javax.swing.JComboBox();
        jComboBox8 = new javax.swing.JComboBox();
        jComboBox9 = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        jComboBox10 = new javax.swing.JComboBox();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        lantai_bersih = new javax.swing.JRadioButton();
        dinding_bersih = new javax.swing.JRadioButton();
        atap_bersih = new javax.swing.JRadioButton();
        pintu_bersih = new javax.swing.JRadioButton();
        jendela_bersih = new javax.swing.JRadioButton();
        lantai_kotor = new javax.swing.JRadioButton();
        dinding_kotor = new javax.swing.JRadioButton();
        atap_kotor = new javax.swing.JRadioButton();
        pintu_kotor = new javax.swing.JRadioButton();
        jendela_kotor = new javax.swing.JRadioButton();
        jPanel5 = new javax.swing.JPanel();
        jButton11 = new javax.swing.JButton();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        inputudara = new javax.swing.JTextField();
        input_nilai_cahaya = new javax.swing.JTextField();
        input_lembab = new javax.swing.JTextField();
        input_suh = new javax.swing.JTextField();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        ini_bising = new javax.swing.JRadioButton();
        ini_gakbising = new javax.swing.JRadioButton();
        ini_gakbau = new javax.swing.JRadioButton();
        ini_bau = new javax.swing.JRadioButton();
        ini_bocor = new javax.swing.JRadioButton();
        ini_gakbocor = new javax.swing.JRadioButton();
        ada_rusak = new javax.swing.JRadioButton();
        gak_ada_rusak = new javax.swing.JRadioButton();
        sudah_aus = new javax.swing.JRadioButton();
        durung_aus = new javax.swing.JRadioButton();
        jButton13 = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        kokoh_1 = new javax.swing.JRadioButton();
        kunciada = new javax.swing.JRadioButton();
        RD_aman = new javax.swing.JRadioButton();
        tidak = new javax.swing.JRadioButton();
        kunchilang = new javax.swing.JRadioButton();
        kokoh_2 = new javax.swing.JRadioButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();

        jButton9.setText("Kembali");

        jButton10.setText("Simpan & Lanjut");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jLabel1.setText("Lokasi Ruang");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "GKB 1", "GKB 2", "GKB 3" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabel2.setText("Nama Ruang");

        inputnama_ruang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputnama_ruangActionPerformed(evt);
            }
        });

        jLabel4.setText("Fakultas / Jurusan");

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Agama Islam", "Ekonomi dan Bisnis", "Hukum", "Ilmu Kesehatan", "Ilmu Sosial dan Politik", "Kedokteran", "Keguruan & Ilmu Pendidikan", "Pertanian dan Peternakan", "Psikologi", "Teknik", "" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        jButton1.setText("Batal");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        input_jurusan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                input_jurusanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 311, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addGap(125, 125, 125))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(39, 39, 39)
                                .addComponent(input_jurusan, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(inputnama_ruang, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputnama_ruang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(input_jurusan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 165, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Identitas Ruang", jPanel1);

        jLabel9.setText("Panjang ruang");

        jLabel10.setText("Lebar ruang");

        jLabel11.setText("Jumlah kursi");

        jLabel12.setText("Jumlah pintu");

        jLabel13.setText("Jumlah jendela");

        jButton7.setText("Batal");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setText("Simpan & Lanjut");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 311, Short.MAX_VALUE)
                        .addComponent(jButton7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton8))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel12))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(input_p, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(28, 28, 28)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(input_kursi, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(input_l, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(j_pintu, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(j_jendela, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addComponent(jLabel13))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(input_p, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(input_l, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(input_kursi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(j_pintu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(j_jendela, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 183, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton8)
                    .addComponent(jButton7))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Kondisi Ruang", jPanel2);

        jLabel5.setText("Stop Kontak");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Posisi Sarana");

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Di pojok", "Dekat dosen", "Jauh" }));

        RD_kontak1.setText("Baik");
        RD_kontak1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RD_kontak1ActionPerformed(evt);
            }
        });

        RD_kontak2.setText("Rusak");
        RD_kontak2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RD_kontak2ActionPerformed(evt);
            }
        });

        jButton5.setText("Batal");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("Simpan & Lanjut");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jLabel8.setText("Kabel LCD");

        jLabel24.setText("Lampu");

        jLabel25.setText("Kipas Angin");

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel26.setText("Jumlah Sarana");

        jLabel27.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel27.setText("Kondisi Sarana");

        jLabel28.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel28.setText("Internet");

        jLabel22.setText("AC");

        jLabel29.setText("CCTV");

        RD_LCD1.setText("Berfungsi");
        RD_LCD1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RD_LCD1ActionPerformed(evt);
            }
        });

        RD_LCD2.setText("Tidak");

        RD_lampu2.setText("Rusak");

        RD_lampu1.setText("Baik");

        RD_kipas2.setText("Rusak");

        RD_kipas1.setText("Baik");

        RD_AC2.setText("Rusak");

        RD_AC1.setText("Baik");

        RD_CCTV1.setText("Baik");

        RD_Login2.setText("Tidak");

        RD_CCTV2.setText("Rusak");

        RD_Login1.setText("Ya");

        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Dekat dosen", "Jauh" }));

        jComboBox6.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Atap ruangan", "Tidak ada" }));

        jComboBox7.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Atap ruangan", "Bawah ruangan" }));

        jComboBox8.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Di belakang", "Di samping", "Di luar" }));

        jComboBox9.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Depan dan belakang" }));

        jLabel7.setText("Pilih SSID");

        jComboBox10.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "UMM Hotspot", "Lain-lain" }));

        jLabel14.setText("Masukkan Bandwidth");

        jLabel15.setText("Apakah Bisa Login?");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton6)
                .addContainerGap())
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jComboBox10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(23, 23, 23)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jTextField16, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(27, 27, 27)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel15)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(RD_Login1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(RD_Login2))))
                            .addComponent(jLabel28))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(15, 15, 15)
                                        .addComponent(jLabel26))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel8)
                                            .addComponent(jLabel24)
                                            .addComponent(jLabel22)
                                            .addComponent(jLabel29))
                                        .addGap(28, 28, 28)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextField13, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextField14, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextField15, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(34, 34, 34)
                                        .addComponent(RD_kontak1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel27)
                                        .addGap(61, 61, 61))))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel25)
                                .addGap(92, 92, 92)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(RD_lampu1)
                                            .addComponent(RD_kipas1)
                                            .addComponent(RD_AC1)
                                            .addComponent(RD_CCTV1))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(RD_kipas2)
                                            .addComponent(RD_CCTV2)
                                            .addComponent(RD_AC2)
                                            .addComponent(RD_lampu2)))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(RD_LCD1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(RD_kontak2)
                                            .addComponent(RD_LCD2))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel6)
                            .addComponent(jComboBox9, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboBox4, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboBox5, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboBox6, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboBox7, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboBox8, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(42, 42, 42))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(jLabel27))
                    .addComponent(jLabel26))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(RD_LCD2)
                            .addComponent(RD_LCD1)
                            .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBox6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(RD_lampu2)
                            .addComponent(RD_lampu1)
                            .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel24))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBox7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(RD_kipas2)
                            .addComponent(RD_kipas1)
                            .addComponent(jTextField13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel25))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBox8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(RD_AC2)
                            .addComponent(RD_AC1)
                            .addComponent(jTextField14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel22))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBox9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(RD_CCTV2)
                            .addComponent(RD_CCTV1)
                            .addComponent(jTextField15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel29)))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(RD_kontak1)
                        .addComponent(RD_kontak2)))
                .addGap(18, 18, 18)
                .addComponent(jLabel28)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel14)
                        .addComponent(jLabel15)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RD_Login1)
                    .addComponent(RD_Login2)
                    .addComponent(jComboBox10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton6)
                    .addComponent(jButton5))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Kondisi Sarana", jPanel3);

        jButton3.setText("Batal");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel16.setText("Kondisi lantai");

        jLabel17.setText("Kondisi dinding");

        jLabel18.setText("Kondisi atap");

        jLabel19.setText("Kondisi pintu");

        jLabel20.setText("Kondisi jendela");

        buttonGroup1.add(lantai_bersih);
        lantai_bersih.setText("Bersih");

        buttonGroup1.add(dinding_bersih);
        dinding_bersih.setText("Bersih");

        atap_bersih.setText("Bersih");

        buttonGroup1.add(pintu_bersih);
        pintu_bersih.setText("Bersih");

        jendela_bersih.setText("Bersih");

        buttonGroup1.add(lantai_kotor);
        lantai_kotor.setText("Kotor");

        buttonGroup1.add(dinding_kotor);
        dinding_kotor.setText("Kotor");

        atap_kotor.setText("Kotor");

        buttonGroup1.add(pintu_kotor);
        pintu_kotor.setText("Kotor");

        jendela_kotor.setText("Kotor");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton3)
                        .addGap(125, 125, 125))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17)
                            .addComponent(jLabel16)
                            .addComponent(jLabel18)
                            .addComponent(jLabel19)
                            .addComponent(jLabel20))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(dinding_bersih)
                                .addGap(18, 18, 18)
                                .addComponent(dinding_kotor))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(lantai_bersih)
                                .addGap(18, 18, 18)
                                .addComponent(lantai_kotor))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(atap_bersih)
                                .addGap(18, 18, 18)
                                .addComponent(atap_kotor))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(pintu_bersih)
                                .addGap(18, 18, 18)
                                .addComponent(pintu_kotor))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jendela_bersih)
                                .addGap(18, 18, 18)
                                .addComponent(jendela_kotor)))
                        .addContainerGap(280, Short.MAX_VALUE))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(lantai_bersih)
                    .addComponent(lantai_kotor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(dinding_bersih)
                    .addComponent(dinding_kotor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(atap_bersih)
                    .addComponent(atap_kotor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(pintu_bersih)
                    .addComponent(pintu_kotor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(jendela_bersih)
                    .addComponent(jendela_kotor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 184, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Lingkungan Ruang", jPanel4);

        jButton11.setText("Batal");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        jLabel36.setText("Sirkulasi udara");

        jLabel37.setText("Nilai pencahayaan");

        jLabel38.setText("Tingkat kelembapan");

        jLabel39.setText("Suhu ruangan");

        jLabel40.setText("Celcius");

        jLabel41.setText("(ex: lancar)");

        jLabel42.setText("(0-500)");

        jLabel43.setText("%");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton11)
                        .addGap(125, 125, 125))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel36)
                            .addComponent(jLabel37)
                            .addComponent(jLabel38)
                            .addComponent(jLabel39))
                        .addGap(38, 38, 38)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(input_lembab, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                            .addComponent(input_nilai_cahaya, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(inputudara, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(input_suh))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel40)
                            .addComponent(jLabel41)
                            .addComponent(jLabel42)
                            .addComponent(jLabel43))
                        .addContainerGap(240, Short.MAX_VALUE))))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel36)
                    .addComponent(inputudara, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel41))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel37)
                    .addComponent(input_nilai_cahaya, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel42))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel38)
                    .addComponent(input_lembab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel43))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel39)
                    .addComponent(input_suh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel40))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 173, Short.MAX_VALUE)
                .addComponent(jButton11)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Kebersihan Ruang", jPanel5);

        ini_bising.setText("Bising");

        ini_gakbising.setText("Tidak bising");

        ini_gakbau.setText("Tidak bau");
        ini_gakbau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ini_gakbauActionPerformed(evt);
            }
        });

        ini_bau.setText("Ada bau");

        ini_bocor.setText("Ada kebocoran");

        ini_gakbocor.setText("Tidak bocor");

        ada_rusak.setText("Ada kerusakan");

        gak_ada_rusak.setText("Tidak rusak");

        sudah_aus.setText("Ada keausan");

        durung_aus.setText("Tidak aus");

        jButton13.setText("Batal");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });

        jLabel21.setText("Tingkat kebisingan");

        jLabel23.setText("Tingkat bau");

        jLabel30.setText("Tingkat kebocoran");

        jLabel31.setText("Tingkat kerusakan");

        jLabel32.setText("Tingkat keausan");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton13)
                        .addGap(125, 125, 125))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel21)
                            .addComponent(jLabel23)
                            .addComponent(jLabel30)
                            .addComponent(jLabel31)
                            .addComponent(jLabel32))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ini_bau)
                            .addComponent(ini_bocor)
                            .addComponent(ada_rusak)
                            .addComponent(sudah_aus)
                            .addComponent(ini_bising))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ini_gakbising)
                            .addComponent(ini_gakbau)
                            .addComponent(durung_aus)
                            .addComponent(ini_gakbocor)
                            .addComponent(gak_ada_rusak))
                        .addContainerGap(207, Short.MAX_VALUE))))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(ini_bising)
                                .addComponent(ini_gakbising))
                            .addComponent(jLabel21))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel23)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel30)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel31)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel32))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(ini_bocor)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ada_rusak)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(sudah_aus))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(ini_gakbau)
                                    .addComponent(ini_bau))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ini_gakbocor)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(gak_ada_rusak)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(durung_aus)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 180, Short.MAX_VALUE)
                .addComponent(jButton13)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Kenyamanan Ruang", jPanel6);

        jLabel33.setText("Apakah ruangan ini kokoh?");

        jLabel34.setText("Apakah kunci pintu dan jendela ada?");

        jLabel35.setText("Apakah ruangan ini aman?");

        kokoh_1.setText("Ya");

        kunciada.setText("Ada");

        RD_aman.setText("Aman");
        RD_aman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RD_amanActionPerformed(evt);
            }
        });

        tidak.setText("Tidak");
        tidak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tidakActionPerformed(evt);
            }
        });

        kunchilang.setText("Tidak");

        kokoh_2.setText("Tidak");

        jButton15.setText("Update");
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });

        jButton16.setText("Simpan untuk kondisi lingkungan");
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel33)
                    .addComponent(jLabel34)
                    .addComponent(jLabel35))
                .addGap(34, 34, 34)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(RD_aman)
                    .addComponent(kunciada)
                    .addComponent(kokoh_1))
                .addGap(31, 31, 31)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(kokoh_2)
                    .addComponent(kunchilang)
                    .addComponent(tidak))
                .addContainerGap(149, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton16)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel33)
                    .addComponent(kokoh_1)
                    .addComponent(kokoh_2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel34)
                    .addComponent(kunciada)
                    .addComponent(kunchilang))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel35)
                    .addComponent(RD_aman)
                    .addComponent(tidak))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 236, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton15)
                    .addComponent(jButton16))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Keamanan Ruang", jPanel7);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ini_gakbauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ini_gakbauActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ini_gakbauActionPerformed

    private void RD_kontak1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RD_kontak1ActionPerformed
        
// TODO add your handling code here:
    }//GEN-LAST:event_RD_kontak1ActionPerformed

    private void RD_kontak2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RD_kontak2ActionPerformed
        
// TODO add your handling code here:
    }//GEN-LAST:event_RD_kontak2ActionPerformed

    private void RD_LCD1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RD_LCD1ActionPerformed
        
// TODO add your handling code here:
    }//GEN-LAST:event_RD_LCD1ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
           // isi();
        
// TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
            
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void tidakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tidakActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tidakActionPerformed

    private void RD_amanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RD_amanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RD_amanActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
          kenalan lan=new kenalan();
                    
          lan.setNamaRuang(inputnama_ruang.getText());
          lan.setProgramStudi(input_jurusan.getText());
          String fakultas=(String)jComboBox2.getSelectedItem();
         // String k_lantai;
          if(lantai_bersih.isSelected()){
                lan.setBersihlantai(lantai_bersih.getText());
                
          }else if(lantai_kotor.isSelected()){
                lan.setBersihlantai(lantai_kotor.getText());
                
          }
          
          if(dinding_bersih.isSelected()){
                lan.setBersihdinding(dinding_bersih.getText());
                
          }else if(dinding_kotor.isSelected()){
                lan.setBersihdinding(dinding_kotor.getText());
                
          }
          
          if(atap_bersih.isSelected()){
                lan.setBersihatap(atap_bersih.getText());
                
          }else if(atap_kotor.isSelected()){
                lan.setBersihatap(atap_kotor.getText());
                
          }
          
          if(pintu_bersih.isSelected()){
                lan.setBersihpintu(pintu_bersih.getText());
                
          }else if(pintu_kotor.isSelected()){
                lan.setBersihpintu(pintu_kotor.getText());
                
          }
          
          if(jendela_bersih.isSelected()){
                lan.setBersihjendela(jendela_bersih.getText());
                
          }else if(jendela_kotor.isSelected()){
                lan.setBersihjendela(jendela_kotor.getText());
                
          } 
          
          
          String cahaya=input_nilai_cahaya.getText();
          String sirkulasi=input_nilai_cahaya.getText();
          String lembab=input_lembab.getText();
          String suhu=input_suh.getText();
          String bisingnya = null;
          
          
          String baunya = null;
          if(ini_bau.isSelected()){
              baunya=ini_bau.getText();
              
          }else if(ini_gakbau.isSelected()){
                baunya=ini_gakbau.getText();
                
          }
          
          String bocornya = null;
          if(ini_bocor.isSelected()){
              bocornya=ini_bocor.getText();
              
          }else if(ini_gakbocor.isSelected()){
              bocornya=ini_gakbocor.getText();
              
          }
          
          String rusaknya = null;
          if(ada_rusak.isSelected()){
              rusaknya=ada_rusak.getText();
              
          }else if(gak_ada_rusak.isSelected()){
              rusaknya=gak_ada_rusak.getText();
              
          }
          
          String ausnya = null;
          if(sudah_aus.isSelected()){
              ausnya=sudah_aus.getText();
              
          }else if(durung_aus.isSelected()){
              ausnya=durung_aus.getText();
              
          }
          
          String kokohnya = null;
          if(kokoh_1.isSelected()){
              kokohnya=kokoh_1.getText();
              
          }else if(kokoh_2.isSelected()){
              kokohnya=kokoh_2.getText();
              
          }
          
          String kuncinya = null;
          if(kunciada.isSelected()){
              kuncinya=kunciada.getText();
              
          }else if(kunchilang.isSelected()){
            kuncinya=kunchilang.getText();
            
          }
          
          String amannya;
          if(RD_aman.isSelected()){
              amannya=RD_aman.getText();
              
          }else if(tidak.isSelected()){
              amannya=tidak.getText();
              
          }
          
          
          
          try{
            Connection c=Koneksinya_ruang.getKonksi();
            String sql="INSERT INTO LINGKUNGAN VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)";
            PreparedStatement p=c.prepareStatement(sql);
            p.setString(1, lan.getNamaRuang());
//            p.setString(2,lan.getProgramStudi());
//            p.setString(3, fakultas);
            p.setString(2, lan.getBersihlantai());
            p.setString(3, lan.getBersihdinding());
            p.setString(4, lan.getBersihatap());
            p.setString(5, lan.getBersihpintu());
            p.setString(6, lan.getBersihjendela());
            p.setString(7, cahaya);
            p.setString(8, sirkulasi);
            p.setString(9, lembab);
            p.setString(10, suhu);
            p.setString(11, bisingnya);
            p.setString(12, baunya);
            p.setString(13, bocornya);
            p.setString(14, rusaknya);
            p.setString(15, ausnya);
            p.setString(16, kokohnya);
            p.setString(17, kuncinya);
            JOptionPane.showMessageDialog(this, "data berhasil di isi");
            p.executeUpdate();
            p.close();
          }
          catch(SQLException t){
              JOptionPane.showMessageDialog(this, "ada yang error saat isi data");
          }
          
    }//GEN-LAST:event_jButton16ActionPerformed

    private void input_jurusanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_input_jurusanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_input_jurusanActionPerformed

    private void inputnama_ruangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputnama_ruangActionPerformed
       
        // TODO add your handling code here:
    }//GEN-LAST:event_inputnama_ruangActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        // TODO add your handling code here:
        kenalan lan=new kenalan();
          lan.setNamaRuang(inputnama_ruang.getText());
          lan.setProgramStudi(input_jurusan.getText());
          String fakultas=(String)jComboBox2.getSelectedItem();
         // String k_lantai;
          if(lantai_bersih.isSelected()){
             lan.setBersihlantai(lantai_bersih.getText());
          }else if(lantai_kotor.isSelected()){
              lan.setBersihlantai(lantai_kotor.getText());
          }
          
          if(dinding_bersih.isSelected()){
              lan.setBersihdinding(dinding_bersih.getText());
          }else if(dinding_kotor.isSelected()){
              lan.setBersihdinding(dinding_kotor.getText());
          }
          
          if(atap_bersih.isSelected()){
              lan.setBersihatap(atap_bersih.getText());
          }else if(atap_kotor.isSelected()){
              lan.setBersihatap(atap_kotor.getText());
          }
          
          if(pintu_bersih.isSelected()){
              lan.setBersihpintu(pintu_bersih.getText());
          }else if(pintu_kotor.isSelected()){
              lan.setBersihpintu(pintu_kotor.getText());
          }
          
          if(jendela_bersih.isSelected()){
              lan.setBersihjendela(jendela_bersih.getText());
          }else if(jendela_kotor.isSelected()){
              lan.setBersihjendela(jendela_kotor.getText());
          } 
          
          
          String cahaya=input_nilai_cahaya.getText();
          String sirkulasi=input_nilai_cahaya.getText();
          String lembab=input_lembab.getText();
          String suhu=input_suh.getText();
          
          String bisingnya = null;
          if(ini_bising.isSelected()){
              bisingnya=ini_bising.getText();
          }else if(ini_gakbising.isSelected()){
              bisingnya=ini_gakbising.getText();
          }
          
          String baunya = null;
          if(ini_bau.isSelected()){
              baunya=ini_bau.getText();
          }else if(ini_gakbau.isSelected()){
            baunya=ini_gakbau.getText();
          }
          
          String bocornya = null;
          if(ini_bocor.isSelected()){
              bocornya=ini_bocor.getText();
          }else if(ini_gakbocor.isSelected()){
              bocornya=ini_gakbocor.getText();
          }
          
          String rusaknya = null;
          if(ada_rusak.isSelected()){
              rusaknya=ada_rusak.getText();
          }else if(gak_ada_rusak.isSelected()){
              rusaknya=gak_ada_rusak.getText();
          }
          
          String ausnya = null;
          if(sudah_aus.isSelected()){
              ausnya=sudah_aus.getText();
          }else if(durung_aus.isSelected()){
              ausnya=durung_aus.getText();
          }
          
          String kokohnya = null;
          if(kokoh_1.isSelected()){
              kokohnya=kokoh_1.getText();
          }else if(kokoh_2.isSelected()){
              kokohnya=kokoh_2.getText();
          }
          
          String kuncinya = null;
          if(kunciada.isSelected()){
              kuncinya=kunciada.getText();
          }else if(kunchilang.isSelected()){
            kuncinya=kunchilang.getText();
          }
          
          String amannya;
          if(RD_aman.isSelected()){
              amannya=RD_aman.getText();
          }else if(tidak.isSelected()){
              amannya=tidak.getText();
          }
          
          
          
          try{
            Connection c=Koneksinya_ruang.getKonksi();
            String sql="UPDATE LINGKUNGAN SET KONDISI_LANTAI=?,KONDISI_DINDING=?,KONDISI_ATAP=?,"
                    + "KONDISI_PINTU=?,KONDISI_JENDELA=?,SIRKULASI=?,NILAI_CAHAYA=?,TINGKAT_LEMBAB=?,"
                   + "SUHU=?,BISING=?,BAU=?,BOCOR=?,RUSAK=?,AUS=?,KOKOH=?,KUNCI_ADA=? WHERE NAMA_RUANG=?";
            PreparedStatement p=c.prepareStatement(sql);
           // p.setString(1, lan.getNamaRuang());
//            p.setString(2,lan.getProgramStudi());
//            p.setString(3, fakultas);
            p.setString(1, lan.getBersihlantai());
            p.setString(2, lan.getBersihdinding());
            p.setString(3, lan.getBersihatap());
            p.setString(4, lan.getBersihpintu());
            p.setString(5, lan.getBersihjendela());
            p.setString(6, cahaya);
            p.setString(7, sirkulasi);
            p.setString(8, lembab);
            p.setString(9, suhu);
            p.setString(10, bisingnya);
            p.setString(11, baunya);
            p.setString(12, bocornya);
            p.setString(13, rusaknya);
            p.setString(14, ausnya);
            p.setString(15, kokohnya);
            p.setString(16, kuncinya);
            p.setString(17, lan.getNamaRuang());
            JOptionPane.showMessageDialog(this, "berhasil update");
            p.executeUpdate();
            p.close();
          }
          catch(SQLException t){
              JOptionPane.showMessageDialog(this, "ada yang error saat ubah data"+t);
          }
          
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        String nm_ruang=inputnama_ruang.getText();
        String lokasi=(String)jComboBox1.getSelectedItem().toString();
        String fakultas=jComboBox2.getSelectedItem().toString();
        String jurusan=input_jurusan.getText();
        String p=input_p.getText();
        String l=input_l.getText();
        String kursi=input_kursi.getText();
        String pintu=j_pintu.getText();
        String jendela=j_jendela.getText();
        
         try{
             Connection c=Koneksinya_ruang.getKonksi();
             String sql="INSERT INTO IDENTITAS VALUES(?,?,?,?,?,?,?,?,?)";
             PreparedStatement pre=c.prepareStatement(sql);
             pre.setString(1, nm_ruang);
             pre.setString(2, lokasi);
             pre.setString(3, fakultas);
             pre.setString(4, jurusan);
             pre.setString(5, p);
             pre.setString(6, l);
             pre.setString(7, kursi);
             pre.setString(8, pintu);
             pre.setString(9, jendela);
             pre.executeUpdate();
             pre.close();
             JOptionPane.showMessageDialog(this, "data di save");
         }catch(SQLException e){
             System.out.println("");
            JOptionPane.showMessageDialog(this, "ada yang error saat isi data"+"/n"+e);
         }    
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        pilih.setVisible(true);
        dispose();
// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        pilih.setVisible(true);
        dispose();
// TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        pilih.setVisible(true);
        dispose();
// TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        pilih.setVisible(true);
        dispose();
// TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        pilih.setVisible(true);
        dispose();
// TODO add your handling code here:
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        pilih.setVisible(true);
        dispose();
// TODO add your handling code here:
    }//GEN-LAST:event_jButton13ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JadiGUI_Isi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JadiGUI_Isi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JadiGUI_Isi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JadiGUI_Isi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JadiGUI_Isi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton RD_AC1;
    private javax.swing.JRadioButton RD_AC2;
    private javax.swing.JRadioButton RD_CCTV1;
    private javax.swing.JRadioButton RD_CCTV2;
    private javax.swing.JRadioButton RD_LCD1;
    private javax.swing.JRadioButton RD_LCD2;
    private javax.swing.JRadioButton RD_Login1;
    private javax.swing.JRadioButton RD_Login2;
    private javax.swing.JRadioButton RD_aman;
    private javax.swing.JRadioButton RD_kipas1;
    private javax.swing.JRadioButton RD_kipas2;
    private javax.swing.JRadioButton RD_kontak1;
    private javax.swing.JRadioButton RD_kontak2;
    private javax.swing.JRadioButton RD_lampu1;
    private javax.swing.JRadioButton RD_lampu2;
    private javax.swing.JRadioButton ada_rusak;
    private javax.swing.JRadioButton atap_bersih;
    private javax.swing.JRadioButton atap_kotor;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JRadioButton dinding_bersih;
    private javax.swing.JRadioButton dinding_kotor;
    private javax.swing.JRadioButton durung_aus;
    private javax.swing.JRadioButton gak_ada_rusak;
    private javax.swing.JRadioButton ini_bau;
    private javax.swing.JRadioButton ini_bising;
    private javax.swing.JRadioButton ini_bocor;
    private javax.swing.JRadioButton ini_gakbau;
    private javax.swing.JRadioButton ini_gakbising;
    private javax.swing.JRadioButton ini_gakbocor;
    private javax.swing.JTextField input_jurusan;
    private javax.swing.JTextField input_kursi;
    private javax.swing.JTextField input_l;
    private javax.swing.JTextField input_lembab;
    private javax.swing.JTextField input_nilai_cahaya;
    private javax.swing.JTextField input_p;
    private javax.swing.JTextField input_suh;
    private javax.swing.JTextField inputnama_ruang;
    private javax.swing.JTextField inputudara;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox10;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JComboBox jComboBox4;
    private javax.swing.JComboBox jComboBox5;
    private javax.swing.JComboBox jComboBox6;
    private javax.swing.JComboBox jComboBox7;
    private javax.swing.JComboBox jComboBox8;
    private javax.swing.JComboBox jComboBox9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField j_jendela;
    private javax.swing.JTextField j_pintu;
    private javax.swing.JRadioButton jendela_bersih;
    private javax.swing.JRadioButton jendela_kotor;
    private javax.swing.JRadioButton kokoh_1;
    private javax.swing.JRadioButton kokoh_2;
    private javax.swing.JRadioButton kunchilang;
    private javax.swing.JRadioButton kunciada;
    private javax.swing.JRadioButton lantai_bersih;
    private javax.swing.JRadioButton lantai_kotor;
    private javax.swing.JRadioButton pintu_bersih;
    private javax.swing.JRadioButton pintu_kotor;
    private javax.swing.JRadioButton sudah_aus;
    private javax.swing.JRadioButton tidak;
    // End of variables declaration//GEN-END:variables

//    @Override
//    public void isi() {
//       try{
//           FileWriter tulis=new FileWriter("lingkungankelas.txt");
//           File file=new File("lingkungankelas.txt");
//           if(file.exists()){
//               JOptionPane.showMessageDialog(this, "data telah di save");
//           }else{
//               JOptionPane.showMessageDialog(this, "file hilang");
//           }
//           
//           
//           if(jComboBox2.getSelectedItem().toString()!=null){
//          
//             tulis.write(jComboBox2.getSelectedItem().toString());
//          
//         }
//           
//           
//           
//           tulis.write(input_jurusan.getText());
//           
//           
//           if(lantai_bersih.isSelected()){
//              tulis.write(lantai_bersih.getText());
//           }else if(lantai_kotor.isSelected()){
//               tulis.write(lantai_kotor.getText());
//           }
//           
//           if(dinding_bersih.isSelected()){
//               tulis.write(pintu_bersih.getText());
//           }else if(dinding_kotor.isSelected()){
//               tulis.write(pintu_kotor.getText());
//           }
//           
//           if(atap_bersih.isSelected()){
//               tulis.write(atap_bersih.getText());
//           }else if(atap_kotor.isSelected()){
//               tulis.write(atap_kotor.getText());
//           }
//           
//           if(pintu_bersih.isSelected()){
//               tulis.write(pintu_bersih.getText());
//           }else if(pintu_kotor.isSelected()){
//               tulis.write(pintu_kotor.getText());
//           }
//           
//           if(jendela_bersih.isSelected()){
//               tulis.write(jendela_bersih.getText());
//           }else if(jendela_kotor.isSelected()){
//               tulis.write(jendela_kotor.getText());
//           }
//           
//           String jurusan;
//           String fakultas;
//           
////        
//          
//           String udara=inputudara.getText();
//           tulis.write(udara);
//           
//           String  cahaya=input_nilai_cahaya.getText();
//           tulis.write(cahaya);
//           tulis.close();
//       }catch(IOException t){
//           System.out.println("gagal input data");
//           t.printStackTrace();
//       }
//    }
//
//    
}
